### ISSUE TITLE
For project week, don't reinvent the wheel...

### ISSUE THREAD

**Issue by ROgbonna1** [Seal125/UJournal#4]
We spend a lot of time building our apps from scratch during learning week so that you can understand core concepts and debug intelligently. During project week, the goal is to get a working product out. The beauty of Node is that we can rely on the NPM ecosystem to allow us to do more than we could have ever done alone. What packages can you pull in to push the pace of development for this app? For example:

- For input validation, use [Validator](https://www.npmjs.com/package/validator)
- Wouldn't it be cool if users could format their blog posts in markdown and you could render them as html? There's [Markdown It](https://www.npmjs.com/package/markdown-it) for that?
- You used some NLP to analyze song lyrics. How about some sentiment analysis out of the box so that you can possibly suggest moods based on what a user has typed?  Check out [Sentiment](https://www.npmjs.com/package/sentiment)

**Comment by emtes** [comment]
Thank you for the resources! We'll definitely make use of Validator and Markdown It! We were on the lookout for a markdown rendering library. We're discussing Sentiment to see if its implementation facilitates the experience we want to build or if it deviates from it in some way because of how we're envisioning the structure of moods.
